
Select MANV, TENNV
From HOADON HD, NHANVIEN NV
Where HD.MANVLAP=NV.MANV and
TONGGIATRI>= ALL (SELECT MAX(TONGGIATRI)
			FROM HOADON);


Select NHANVIEN.MaLoai, TENLOAI, Count (MANV)
From LOAINV, NHANVIEN
Where LOAINV.MALOAI=NHANVIEN.MALOAI
Group by NHANVIEN.MaLoai, TENLOAI
Having Count( MANV) >= ALL (Select Count (MANV)
				From NHANVIEN
				Group by MALOAI );

Select SUM(TONGGIATRI)
From HOADON
Where (DAY(NGAYLAP)=11 AND MONTH(NGAYLAP)=6) OR (DAY(NGAYLAP)=12 AND MONTH(NGAYLAP)=6);

 Select LINHKIEN.MALINHKIEN, VITRILINHKIEN, THOIGIANBAOHANH, TENLOAITEM, LINHKIEN.MAKHO
From LINHKIEN_KHO, LINHKIEN, TEMBAOHANH, KHO
Where LINHKIEN_KHO.MaLinhKien=LINHKIEN.MaLinhKien and LINHKIEN.MATEM=TEMBAOHANH.MATEM and KHO.MAKHO= LINHKIEN.MAKHO ;

SELECT TENKH, DIACHI
FROM HOADON
GROUP BY TENKH, DIACHI
HAVING COUNT(MAHOADON)>2;

SELECT MAHOADON, MANV, TENNV
FROM HOADON HD,NHANVIEN NV
WHERE
    HD.MANVLAP=NV.MANV And
    TENKH IN ( SELECT TENKH
                      FROM HOADON
                      GROUP BY TENKH
                      HAVING COUNT(MAHOADON)>2);


SELECT KHO.MAKHO,VITRI, TENLINHKIEN
FROM KHO, LINHKIEN
WHERE
KHO.MAKHO=LINHKIEN.MAKHO
AND MADANHMUC= (SELECT MADANHMUC
                               FROM LINHKIEN
                               GROUP BY MADANHMUC
                               HAVING COUNT(MALINHKIEN)>= ALL(SELECT COUNT(MALINHKIEN)
                                                     FROM LINHKIEN
                                                             GROUP BY MADANHMUC))
AND DONGIA>500000;

SELECT NV.MANV, NV.TENNV, SUM(TONGGIATRI)
FROM NHANVIEN NV, HOADON HD
WHERE NV.MANV=HD.MANVLAP
GROUP BY MANV, TENNV
ORDER BY SUM(TONGGIATRI) ASC;

SELECT MANVLAP, TENNV
FROM NHANVIEN NV, HOADON HD
WHERE
HD.MANVLAP= NV.MANV
AND MANV IN( SELECT MANV
             FROM NHANVIEN NF, HOADON HF
             WHERE
             HF.MANVLAP= NF.MANV              
             GROUP BY MANV
       	 HAVING COUNT(MAHOADON) >5)
GROUP BY MANVLAP, TENNV
HAVING AVG(TONGGIATRI)>300000;



